"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['LoginForm.py']
DATA_FILES = ['./config.yml']
OPTIONS = {
    'plist':{
                'CFBundleName'   : 'Class Table Tool',     # 应用名
                'CFBundleDisplayName': '宁大课表工具', # 应用显示名
                'CFBundleVersion': '1.4.1-20251117-CustomTkinter',      # 应用版本号
                'CFBundleIdentifier' : 'me.z.classtabletool', # 应用包名、唯一标识
                'NSHumanReadableCopyright': 'Copyright © 2025 Neighborhood of Z. All rights reserved.', # 可读版权
            },
    'excludes': [
        'PyQt5',
        'PyQt6',
        'PyInstaller',
        'numpy',
        'cffi',
        'PIL',
        'cryptography',
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
