"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./LoginForm.py']
DATA_FILES = ['./LoginForm.py','./app/','./utils/','./config.yml']
OPTIONS = {
#   'iconfile':'earth.icns',
            'plist':{
                    'CFBundleName'   : 'Class Table Tool',     # 应用名
                    'CFBundleDisplayName': '宁大课表工具', # 应用显示名
                    'CFBundleVersion': '1.4-20251019',      # 应用版本号
                    'CFBundleIdentifier' : 'me.z.classtabletool', # 应用包名、唯一标识
                    'NSHumanReadableCopyright': 'Copyright © 2025 Neighborhood of Z. All rights reserved.', # 可读版权
#           'includes': ['sip', 'PyQt5.QtCore', 'PyQt5.QtWidgets']
                    }
                
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
