"""
This is a setup.py script generated by py2applet

Usage:
    python setup_pyqt.py py2app
"""

from setuptools import setup
import sys
from __version__ import (
    __build__,
    __version__,
)

minorVer = sys.version_info.minor
if minorVer<14:
    MinimumSystemVersion = '10.14.0'
else:
    MinimumSystemVersion = '10.15.0'

APP = ['LoginForm_pyqt.py']
# DATA_FILES = ['./config.yml']
OPTIONS = {
    # 'iconfile':'NBUClassTableTool.icns',
    'plist':{
                'CFBundleName'   : f'Class_Table_Tool_macOS_{__version__}_Qt',     # 应用名
                'CFBundleDisplayName': '宁大课表工具', # 应用显示名
                'CFBundleVersion': f'{__version__}-{__build__}-PyQt6',      # 应用版本号
                'CFBundleIdentifier' : 'me.z.classtabletoolqt', # 应用包名、唯一标识
                'NSHumanReadableCopyright': ' ', # 可读版权
                'LSMinimumSystemVersion': MinimumSystemVersion,
            },
    'excludes': [
        'PyQt5',
        'PyInstaller',
        'numpy',
        'cffi',
        'PIL',
        'cryptography',
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
